### ISSUE TITLE
Vueditor does not work with latest VueJS (2.4.1)

### ISSUE THREAD

**Issue by andreixk** [hifarer/vueditor#18]
The example shows:

`import "vueditor/dist/css/vueditor.min.css";`
but that file does not exist, there's vueditor.min.css in dist/style directory. if i include that, it gives error:
`cannot read property 'title' of undefined`
If I downgrade to vueditor@0.2.4 then I get a Vue warning:
`Do not use built-in or reserved HTML elements as component id: iframe`
`Do not use built-in or reserved HTML elements as component id: picture`

**Comment by hifarer** [comment]
hi there, it is a bug and i fixed it now, please update via `npm i vueditor` and check the new doc.

**Comment by andreixk** [comment]
Now i'm getting this error:

```
[Vue warn]: Error in render function: "TypeError: Cannot read property 'title' of undefined"

found in

---> <VeToolbar>
       <Vueditor>
```

**Comment by wspl** [comment]
similar bugs here
```
vue.esm.js?65d7:434[Vue warn]: Error in callback for watcher "content": "TypeError: Cannot set property 'status' of undefined"

found in

---> <VeUndo>
       <Vueditor>
         <FormEditor> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormEditor.vue
           <FormGroup> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormGroup.vue
             <FormFrame> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormFrame.vue
               <CreativeNew> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/CreativeNew.vue
                 <Creative> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Creative.vue
                   <App> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/App.vue
                     <Root>warn @ vue.esm.js?65d7:434handleError @ vue.esm.js?65d7:519run @ vue.esm.js?65d7:2864flushSchedulerQueue @ vue.esm.js?65d7:2615(anonymous function) @ vue.esm.js?65d7:655nextTickHandler @ vue.esm.js?65d7:602
vue.esm.js?65d7:523TypeError: Cannot set property 'status' of undefined(…)handleError @ vue.esm.js?65d7:523run @ vue.esm.js?65d7:2864flushSchedulerQueue @ vue.esm.js?65d7:2615(anonymous function) @ vue.esm.js?65d7:655nextTickHandler @ vue.esm.js?65d7:602
vue.esm.js?65d7:434[Vue warn]: Error in callback for watcher "content": "TypeError: Cannot set property 'status' of undefined"

found in

---> <VeUndo>
       <Vueditor>
         <FormEditor> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormEditor.vue
           <FormGroup> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormGroup.vue
             <FormFrame> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Form/FormFrame.vue
               <CreativeNew> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/CreativeNew.vue
                 <Creative> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/components/Creative.vue
                   <App> at /Users/Plutonist/Documents/Projects/unimoe-frontend/src/App.vue
                     <Root>warn @ vue.esm.js?65d7:434handleError @ vue.esm.js?65d7:519run @ vue.esm.js?65d7:2864flushSchedulerQueue @ vue.esm.js?65d7:2615(anonymous function) @ vue.esm.js?65d7:655nextTickHandler @ vue.esm.js?65d7:602
vue.esm.js?65d7:523TypeError: Cannot set property 'status' of undefined
    at UPDATE_BUTTON_STATES (eval at <anonymous> (http://localhost:8080/app.js:1922:1), <anonymous>:5:63624)
    at wrappedMutationHandler (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:597:5)
    at commitIterator (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:321:7)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:320:11)
    at Store._withCommit (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:408:3)
    at Store.commit (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:319:8)
    at boundCommit (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:275:19)
    at t.updateButtonStates (eval at <anonymous> (http://localhost:8080/app.js:1922:1), <anonymous>:5:62908)
    at Array.wrappedActionHandler (eval at <anonymous> (http://localhost:8080/app.js:1910:1), <anonymous>:604:15)
```

**Comment by hifarer** [comment]
hi, i can't reproduce the issue with version 0.2.8, is there any possibility that you are still using the old version? can you paste your example code here?

**Comment by andreixk** [comment]
To reproduce: 
create a new project with `vue init test`, 
then add vueditor and vuex: `yarn add vuex --dev; yarn add vueditor --dev`

main.js:
```javascript
let editCfg = {
  toolbar: [
      'undo', 'fontName', 'fontSize', 'foreColor', 'backColor', 'bold', 'italic', 'underline', 'strikeThrough', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'
    ],
    fontName: [
      {val: "Arial"}, {val: "Courier New"}, {val: "Times New Roman"}, {val: "Verdana"}
    ],
  lang:'en',
    // the font-size select's options 
    fontSize: ['8pt','10pt','11pt','12pt','13pt','14pt','16pt','18pt','20pt','24pt','28pt'],
 }
Vue.use(Vueditor,editCfg);
```

app.vue:
```html
<template>
  <div id="app">
    <Vueditor></Vueditor>
  </div>
</template>

<script>

export default {
  name: 'app',
}
</script>
```

**Comment by hifarer** [comment]
@andreixk The `lang` attribute in config while initializing is no longer a string now. It should be an object. Please check the new doc.

**Comment by hifarer** [comment]
Just remove `lang:'en'` and it will work, I'll add some type check for the config in later version.

**Comment by crazylxr** [comment]
but you don't write what is an object for the lang attribute.
Which object should we fill for the lang attribute
